package com.demo.monorepo.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Generates a module dependency graph in three formats under `docs/`:
 *
 *   - `dependency-graph.json` — machine-readable graph used by
 *                                `tools/affected-modules/affected_modules.py`.
 *   - `dependency-graph.dot`  — Graphviz format (`dot -Tpng ...`).
 *   - `dependency-graph.html` — Standalone HTML preview (no external deps).
 *
 * Run with: `./gradlew generateDependencyGraph`
 */
abstract class GenerateDependencyGraphTask : DefaultTask() {

    init {
        group = "documentation"
        description = "Generates the module dependency graph (json + dot + html)."
    }

    private val outputDir: File = File(project.rootDir, "docs")

    @get:OutputFile
    val jsonFile: File get() = File(outputDir, "dependency-graph.json")

    @get:OutputFile
    val dotFile: File get() = File(outputDir, "dependency-graph.dot")

    @get:OutputFile
    val htmlFile: File get() = File(outputDir, "dependency-graph.html")

    @TaskAction
    fun generate() {
        outputDir.mkdirs()

        val graph = collectGraph()
        jsonFile.writeText(toJson(graph))
        dotFile.writeText(toDot(graph))
        htmlFile.writeText(toHtml(graph))

        logger.lifecycle("[generateDependencyGraph] wrote:")
        logger.lifecycle("  - ${jsonFile.relativeTo(project.rootDir)}")
        logger.lifecycle("  - ${dotFile.relativeTo(project.rootDir)}")
        logger.lifecycle("  - ${htmlFile.relativeTo(project.rootDir)}")
    }

    // -----------------------------------------------------------------------
    // Graph collection
    // -----------------------------------------------------------------------

    private data class ModuleNode(
        val path: String,
        val layer: String,
        val projectDir: String,
        val dependencies: List<String>,
    )

    private fun collectGraph(): List<ModuleNode> {
        val root = project.rootProject
        return root.allprojects
            .filter { it != root }
            .sortedBy { it.path }
            .map { mod ->
                val deps = mod.configurations
                    .filter { it.name in DECLARED_CONFIGS }
                    .flatMap { c ->
                        c.dependencies.filterIsInstance<
                            org.gradle.api.artifacts.ProjectDependency>()
                    }
                    .map { it.dependencyProject.path }
                    .distinct()
                    .sorted()
                ModuleNode(
                    path = mod.path,
                    layer = layerOf(mod),
                    projectDir = mod.projectDir.relativeTo(root.projectDir).path,
                    dependencies = deps,
                )
            }
    }

    private fun layerOf(p: Project): String = when {
        p.path == ":app" -> "app"
        p.path.startsWith(":features:") -> "feature"
        p.path.startsWith(":bizlibs:") -> "bizlib"
        p.path.startsWith(":foundations:") -> "foundation"
        p.path.startsWith(":third-party:") -> "third-party"
        else -> "other"
    }

    // -----------------------------------------------------------------------
    // Serializers (hand-rolled to avoid external deps)
    // -----------------------------------------------------------------------

    private fun toJson(graph: List<ModuleNode>): String = buildString {
        appendLine("{")
        appendLine("  \"modules\": [")
        graph.forEachIndexed { i, m ->
            append("    {")
            append("\"path\": \"${m.path}\", ")
            append("\"layer\": \"${m.layer}\", ")
            append("\"projectDir\": \"${m.projectDir.replace("\\", "/")}\", ")
            append("\"dependencies\": [")
            append(m.dependencies.joinToString(", ") { "\"$it\"" })
            append("]}")
            if (i < graph.lastIndex) append(",")
            appendLine()
        }
        appendLine("  ]")
        appendLine("}")
    }

    private fun toDot(graph: List<ModuleNode>): String = buildString {
        appendLine("// Auto-generated by :generateDependencyGraph")
        appendLine("digraph Modules {")
        appendLine("  rankdir=LR;")
        appendLine("  node [shape=box, style=\"rounded,filled\", fontname=Helvetica];")
        graph.forEach { m ->
            val color = colorOf(m.layer)
            appendLine("  \"${m.path}\" [fillcolor=\"$color\"];")
        }
        appendLine()
        graph.forEach { m ->
            m.dependencies.forEach { dep ->
                appendLine("  \"${m.path}\" -> \"$dep\";")
            }
        }
        appendLine("}")
    }

    private fun colorOf(layer: String): String = when (layer) {
        "app" -> "#FFD580"
        "feature" -> "#A7E8B5"
        "bizlib" -> "#A6CFFF"
        "foundation" -> "#D7BDE2"
        "third-party" -> "#F5B7B1"
        else -> "#EEEEEE"
    }

    private fun toHtml(graph: List<ModuleNode>): String {
        val rows = graph.joinToString("\n") { m ->
            val deps = if (m.dependencies.isEmpty()) {
                "<span class=\"none\">—</span>"
            } else {
                m.dependencies.joinToString(", ") {
                    "<code>$it</code>"
                }
            }
            """
            |        <tr class="layer-${m.layer}">
            |          <td><code>${m.path}</code></td>
            |          <td><span class="badge layer-${m.layer}">${m.layer}</span></td>
            |          <td>$deps</td>
            |        </tr>
            """.trimMargin()
        }

        val edges = graph.flatMap { m ->
            m.dependencies.map { dep -> "${m.path} → $dep" }
        }.joinToString("\n") { "          <li><code>$it</code></li>" }

        return """
        |<!DOCTYPE html>
        |<html lang="zh-CN">
        |<head>
        |  <meta charset="UTF-8" />
        |  <title>Monorepo Demo — Module Dependency Graph</title>
        |  <style>
        |    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
        |           margin: 24px; color: #222; }
        |    h1 { margin-bottom: 4px; }
        |    .subtitle { color: #666; margin-top: 0; }
        |    table { border-collapse: collapse; width: 100%; margin-top: 16px; }
        |    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left;
        |             vertical-align: top; }
        |    th { background: #f3f3f3; }
        |    code { background: #f5f5f5; padding: 2px 6px; border-radius: 4px;
        |           font-family: "SFMono-Regular", Consolas, monospace; font-size: 12px; }
        |    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px;
        |             font-size: 12px; font-weight: 600; color: #333; }
        |    .layer-app        { background: #FFD580; }
        |    .layer-feature    { background: #A7E8B5; }
        |    .layer-bizlib     { background: #A6CFFF; }
        |    .layer-foundation { background: #D7BDE2; }
        |    .layer-third-party{ background: #F5B7B1; }
        |    .none { color: #999; }
        |    .edges { columns: 2 320px; column-gap: 24px; }
        |    .edges li { break-inside: avoid; margin: 2px 0; list-style: none; }
        |  </style>
        |</head>
        |<body>
        |  <h1>Module Dependency Graph</h1>
        |  <p class="subtitle">Generated by <code>./gradlew generateDependencyGraph</code></p>
        |
        |  <h2>Modules (${graph.size})</h2>
        |  <table>
        |    <thead>
        |      <tr><th>Module</th><th>Layer</th><th>Dependencies</th></tr>
        |    </thead>
        |    <tbody>
        |$rows
        |    </tbody>
        |  </table>
        |
        |  <h2>Edges (${graph.sumOf { it.dependencies.size }})</h2>
        |  <ul class="edges">
        |$edges
        |  </ul>
        |
        |  <p style="margin-top:24px;color:#888;font-size:12px;">
        |    Tip: render the .dot file with Graphviz —
        |    <code>dot -Tpng docs/dependency-graph.dot -o graph.png</code>
        |  </p>
        |</body>
        |</html>
        """.trimMargin()
    }

    companion object {
        private val DECLARED_CONFIGS = setOf(
            "api",
            "implementation",
            "compileOnly",
            "runtimeOnly",
            "debugImplementation",
            "releaseImplementation",
        )
    }
}
