#!/usr/bin/env bash
# Install an opt-in git hook that runs check_docs_sync.py after every commit.
# It WARNs only — never blocks a commit — so it's safe to leave on.
#
# Usage:
#   bash tools/docs-sync/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOK_DIR/post-commit"

mkdir -p "$HOOK_DIR"

cat > "$HOOK_FILE" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by tools/docs-sync/install-hooks.sh — DO NOT EDIT.
# Runs the docs-sync check after every commit; prints warnings only.
set -e
if command -v python3 >/dev/null 2>&1; then
  python3 "$(git rev-parse --show-toplevel)/tools/docs-sync/check_docs_sync.py" \
    --base "origin/main" 2>/dev/null || true
fi
EOF

chmod +x "$HOOK_FILE"
echo "[docs-sync] installed post-commit hook at $HOOK_FILE"
echo "[docs-sync] it WARNs only — commits are never blocked locally."
echo "[docs-sync] CI will still enforce the same rules in --strict mode."
